### ISSUE TITLE
XD3_INVALID_INPUT

### ISSUE THREAD

**Issue by FBiDev** [marco-calautti/DeltaPatcher#46]
Hi, i trying to apply a patch (30Mb) to a .iso with 4.03Gb size, and i received this message 

https://imgur.com/a/vRmtYig

if i use a xdelta3.1.0 standalone, i can apply normaly,

**Comment by marco-calautti** [comment]
Very strange. Are you using the 32 bit or the 64 bit version?

**Comment by FBiDev** [comment]
> Very strange. Are you using the 32 bit or the 64 bit version?

using 64bit version

**Comment by FBiDev** [comment]
if interested here are the files:

xdelta:
https://files.catbox.moe/koghxy.zip
ISO:
https://myrient.erista.me/files/Redump/Sony%20-%20PlayStation%202/Kingdom%20Hearts%20II%20-%20Final%20Mix%20%28Japan%29.zip

**Comment by marco-calautti** [comment]
@FBiDev it seems I did not enable support for files larger than 4GB. Can you please test if these new versions (both 32 bit and 64 bit) work?
[windows_bin_x86.zip](https://github.com/marco-calautti/DeltaPatcher/files/15147394/windows_bin_x86.zip)
[windows_bin_x86_64.zip](https://github.com/marco-calautti/DeltaPatcher/files/15147396/windows_bin_x86_64.zip)

**Comment by FBiDev** [comment]
Hi!
Now both exe 32-64 work to apply Patch!!!
But to create a patch, dont work, he produce a xdelta with more than 1gb.
and the original xdelta have only 30mb.

**Comment by marco-calautti** [comment]
This I think it depends on the window size. What value are you using for the -B flag when using the command line?

**Comment by FBiDev** [comment]
in command line fails to create a patch with files greater than 4GB too, only apply if you already have a patch, 
i tested with a file 3.3Gb and works great, produce a xdelta with 11mb, equal your program,
now with a .ISO with 4.03Gb he create xdelta very large

.\xdelta3.exe -B 134217728 -W 8388608 -v -f -e -s 'Original.iso' 'Modified.iso' 'delta.xdelta'

**Comment by FBiDev** [comment]
A Linux user say me that he can create a pach in linux normal using this command line:

xdelta3 -B 4333170688 -W 67108864 -vs "Original.iso" "Modified.iso" "Patch.xdelta3"

for me in Windows, not work, produce a large xdelta file

**Comment by marco-calautti** [comment]
You are probably using a different version of xdelta3. With version 3.1.0 you should get a small patch as expected. As for Delta Patcher, I just need to enable larger window/block sizes.

**Comment by FBiDev** [comment]
My Version:
.\xdelta3.exe -V
Xdelta version 3.1.0, Copyright (C) Joshua MacDonald
Xdelta comes with ABSOLUTELY NO WARRANTY.
This is free software, and you are welcome to redistribute it
under certain conditions; see "COPYING" for details.

With your program i set:
lzma level 5 1024 Window Size
and all files work great wit less 4gb, with 4gb, fails to create small files

**Comment by FBiDev** [comment]
i discovered this issue open in xdelta github, that is from >4Gb files in windows
https://github.com/jmacd/xdelta/issues/127

**Comment by marco-calautti** [comment]
Indeed, there is a bug in the xdelta library, that never got fixed. I don't know if that is the same you are referring to, but I just fixed the bug I found at least. I will test on Windows whether things now work as expected.

**Comment by pizzagamer213** [comment]
The problem persists to this day, and no, that's not a question.
